version: '2'
services:
    apache:
        build: ./docker/apache
        container_name: api_apache
        ports:
          - 81:80
        volumes:
          - ./docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/www/html
        depends_on:
          - php
        networks:
          - default

    mysql:
        image: mysql
        command: ['--default-authentication-plugin=mysql_native_password']
        container_name: api_mysql
        ports:
          - 3307:3306
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
          - default
          
    
    php:
        build: ./docker/php
        container_name: api_php
        volumes:
          - .:/home/www/html
        depends_on:
          - mysql
        networks:
          - default
      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: api_phpmyadmin
        ports:
            - 8081:80
        environment:
          PMA_HOST: mysql
        networks:
          - default

          
networks:
  default: ~

volumes:
  mysql_data:
